# Generated by Django 4.2.1 on 2023-05-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_file_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='feature_vector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
